### ISSUE TITLE
can't run install.php on freebsd server

### ISSUE THREAD

**Issue by zc4r** [lainchan/lainchan#204]
im trying to install lainchan on my freebsd server.
i installed all the dependencies and changed the owner of the folder to chown -R www:www
but now i get this when i run install.php:

Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /usr/local/www/apache24/data/lainchan/lainchan/inc/functions.php on line 1577

Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /usr/local/www/apache24/data/lainchan/lainchan/inc/functions.php on line 1577

Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /usr/local/www/apache24/data/lainchan/lainchan/inc/functions.php on line 1596

Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /usr/local/www/apache24/data/lainchan/lainchan/inc/functions.php on line 1597

Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /usr/local/www/apache24/data/lainchan/lainchan/inc/template.php on line 66

Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /usr/local/www/apache24/data/lainchan/lainchan/inc/template.php on line 75

Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /usr/local/www/apache24/data/lainchan/lainchan/inc/lib/gettext/gettext.inc on line 91

Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /usr/local/www/apache24/data/lainchan/lainchan/inc/lib/gettext/gettext.inc on line 92

Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /usr/local/www/apache24/data/lainchan/lainchan/inc/lib/gettext/gettext.inc on line 94

Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /usr/local/www/apache24/data/lainchan/lainchan/inc/lib/gettext/gettext.inc on line 99

Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /usr/local/www/apache24/data/lainchan/lainchan/inc/lib/gettext/gettext.inc on line 100

Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /usr/local/www/apache24/data/lainchan/lainchan/inc/lib/gettext/gettext.inc on line 102

Warning: Cannot modify header information - headers already sent by (output started at /usr/local/www/apache24/data/lainchan/lainchan/inc/functions.php:1577) in /usr/local/www/apache24/data/lainchan/lainchan/inc/error.php on line 77

Fatal error: Uncaught Error: Call to a member function seekto() on null in /usr/local/www/apache24/data/lainchan/lainchan/inc/lib/gettext/gettext.php:148 Stack trace: #0 /usr/local/www/apache24/data/lainchan/lainchan/inc/lib/gettext/gettext.php(254): gettext_reader->load_tables() #1 /usr/local/www/apache24/data/lainchan/lainchan/inc/lib/gettext/gettext.inc(279): gettext_reader->translate('Error') #2 /usr/local/www/apache24/data/lainchan/lainchan/inc/lib/gettext/gettext.inc(286): _gettext('Error') #3 /usr/local/www/apache24/data/lainchan/lainchan/inc/lib/gettext/gettext.inc(497): __('Error') #4 /usr/local/www/apache24/data/lainchan/lainchan/inc/error.php(81): _('Error') #5 /usr/local/www/apache24/data/lainchan/lainchan/inc/error.php(12): error('Call to a membe...') #6 [internal function]: exception_handler(Object(Error)) #7 {main} thrown in /usr/local/www/apache24/data/lainchan/lainchan/inc/lib/gettext/gettext.php on line 148
Error recursion detected with Caught fatal error: Uncaught Error: Call to a member function seekto() on null in /usr/local/www/apache24/data/lainchan/lainchan/inc/lib/gettext/gettext.php:148 Stack trace: #0 /usr/local/www/apache24/data/lainchan/lainchan/inc/lib/gettext/gettext.php(254): gettext_reader->load_tables() #1 /usr/local/www/apache24/data/lainchan/lainchan/inc/lib/gettext/gettext.inc(279): gettext_reader->translate('Error') #2 /usr/local/www/apache24/data/lainchan/lainchan/inc/lib/gettext/gettext.inc(286): _gettext('Error') #3 /usr/local/www/apache24/data/lainchan/lainchan/inc/lib/gettext/gettext.inc(497): __('Error') #4 /usr/local/www/apache24/data/lainchan/lainchan/inc/error.php(81): _('Error') #5 /usr/local/www/apache24/data/lainchan/lainchan/inc/error.php(12): error('Call to a membe...') #6 [internal function]: exception_handler(Object(Error)) #7 {main} thrown in /usr/local/www/apache24/data/lainchan/lainchan/inc/lib/gettext/gettext.php at line 148
Original error:Call to a member function seekto() on null

**Comment by Appleman1234** [comment]
As mentioned in IRC conversation, can you please confirm what version of PHP you are running ?
